### ISSUE TITLE
Need help ?

### ISSUE THREAD

**Issue by Justkant** [rhumaric/stylelint-plugin-prettier#1]
Hi,

I can help testing or adding features if you need :v:
I want to be able to format with stylelint as I do with eslint.

**Comment by romaricpascal** [comment]
Hi,

That's exactly why I started this project... and then life got in the way of progress a bit :/ I can't commit to any progress on it at the moment, unfortunately.  But I'd be happy to answer questions about the current code if you wish to fork and move forward with the features. As far as I remember, I was struggling with the `--fix` option and passing back the AST to postcss so other stylelint plugins could run after the plugin.

**Comment by Justkant** [comment]
Yo, have you seen [stylelint-prettier](https://github.com/BPScott/stylelint-prettier) ?
I tried it and it seems to work fine :v:

**Comment by romaricpascal** [comment]
That's great, that's exactly what I had in mind when I started but didn't get the time to build. Looks like I can retire this project. I'll update the readme to direct people there. Cheer for the heads up!
