### ISSUE TITLE
Publish in NPM

### ISSUE THREAD

**Issue by fsmaia** [rhumaric/stylelint-plugin-prettier#2]
Could we publish this package in NPM, even as a alpha/beta release? By reading README.md I think current features are enough to an initial release, right?

Thank you!

**Comment by romaricpascal** [comment]
Hello,

The plugin is missing quite a bit of documentation to make worthwhile publication on NPM, imho. 

I reversed the experiments I was making around the `--fix` option to get the repo in a clean state. That might be enough to start using the plugin through NPM via it's git URL. If you wish to have the project on NPM properly, feel free to fork and publish it :) Unfortunately, I can't commit any more to this, but I'll be happy to answer questions about the code if you want to push the features further.

**Comment by romaricpascal** [comment]
The prettier team is now supporting an official plugin published on NPM: https://www.npmjs.com/package/stylelint-prettier. That'll save the publication of this one.
